### ISSUE TITLE
OSProcess and LSP Servers

### ISSUE THREAD

**Issue by darth-cheney** [hpi-swa-lab/sb-tree-sitter#1]
Hi all,

I was pointed this way by the Squeak mailing list ([see this thread)](https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-August/221994.html).
  
So far, I have been unable to launch the `typescript-language-server` from within Squeak, using OSProcess, and I am looking for some pointers. In my case, it appears that I need to be loading node and a bunch of other things first, but the examples in this repository seem to be doing nothing of the sort, so I'm wondering if there is some different strategy.
  
For reference, I am using macOS 12.6

**Comment by tom95** [comment]
Hi @darth-cheney! Our code, too, relies on a lot of node things to be available. To be more precise: you will have to have installed typescript-language-server as directed by their [README](https://github.com/typescript-language-server/typescript-language-server) via `npm install -g typescript-language-server typescript`. Afterwards, it needs to be within your PATH. For example, in my case, nvm (node version manager) added `/home/tom/.nvm/versions/node/v16.16.0/bin` to my PATH, which is an addition that occurs in my bashrc only. Fortunately, I'm also always running squeak via bash, so no troubles here.

In every other case, you will likely have to ensure that both `node` and `typescript-language-server` executables can be run without the additions to your PATH (e.g. by placing symlinks in /usr/local/bin), or that squeak knows about those additional directories, too.

**Comment by tom95** [comment]
Closing for now, please follow up with any more questions if needed :)
