### ISSUE TITLE
Unable to install in Squeak 6 due to Sandblocks-Cpp

### ISSUE THREAD

**Issue by darth-cheney** [hpi-swa-lab/sb-tree-sitter#2]
Hi,
  
I just pulled down a fresh image for Squeak 6 and tried to install this baseline using the README instructions and Metacello is signalling an error when trying to load `Sandblocks-Cpp`. Here's the relevant line in the Transcript output:
  
```
Fetched -> Sandblocks-C-tonel.1 --- github://hpi-swa-lab/sb-tree-sitter:master/packages [5c6cd58:master] --- github://hpi-swa-lab/sb-tree-sitter:master/packages
...RETRY->Sandblocks-Cpp
...RETRY->Sandblocks-Cpp
...FAILED->Sandblocks-Cpp
```

**Comment by darth-cheney** [comment]
Upon looking into the Baseline, it appears that the spec for that package is still listed there even though it's no longer in the repo: 

https://github.com/hpi-swa-lab/sb-tree-sitter/blob/master/packages/BaselineOfSBTreeSitter/BaselineOfSBTreeSitter.class.st#L98
  
Though I'm not sure why just loading (which I assumed loads the 'default' group) doesn't simply skip Cpp as a requirement.

**Comment by tom95** [comment]
Thanks for letting me know! I must have missed the CI mail.

I recently added Cpp to the default set because I stumbled upon some new corner cases with the Cpp grammar I added to the test suite. Admittedly, it would make sense to then only add it as a dependency to the tests baseline group.
