### ISSUE TITLE
Question re: TreeSitter

### ISSUE THREAD

**Issue by darth-cheney** [hpi-swa-lab/sb-tree-sitter#4]
Is the Tree Sitter implementation in this repository a re-implementation of the C library, or does it use the C version underneath?

**Comment by tom95** [comment]
It's part-part.

It contains a functioning reimplementation of the tree-sitter parser with modifications for the purposes of accepting and autocompleting incomplete inputs. In theory, this implementation would also be able to parse complete inputs, just as the C tree-sitter parser. However, I took some shortcuts during the implementation as the scope was limited. So it may not work for all inputs.

As such, in practice, this project makes use of the C implementation for parsing complete files and uses its own parser only for incomplete inputs.

Hope that makes it clear, please feel free to ask further questions :)
